options:
  formatter: stylish
  merge-default-rules: true
rules:
  border-zero: 0
  class-name-format:
    - 1
    - convention: '[sgbp|is-].\w+'
  function-name-format:
    - 1
    - allow-leading-underscore: false
      convention: '[attr|sgbp|_].\w+'
  id-name-format:
    - 1
    - convention: '^[sgbp|is-].\w+$'
  leading-zero: 0
  mixin-name-format:
    - 1
    - allow-leading-underscore: false
      convention: '[sgbp|_].\w+'
  no-css-comments: 0
  no-trailing-zero: 0
  placeholder-name-format:
    - 1
    - convention: '[sgbp|is-].\w+'
  property-sort-order: 0
  shorthand-values: 0
  variable-name-format:
    - 1
    - allow-leading-underscore: false
      convention: '[sgbp|_].\w+'
  zero-unit: 0
  empty-args: 0
  force-element-nesting: 0
  force-attribute-nesting: 0
  force-pseudo-nesting: 0
  nesting-depth:
    - 1
    - max-depth: 3
  no-color-keywords: 0
